# Notebook for computing hashes, buckets and similarity values for the disk scheme using a hybrid approach

Utilizes the disk scheme

Incorporates:
* Hashing of trajectories using disk scheme
* Bucketing of hashes made from disk scheme
* Similarity computation between trajectories within buckets.
    * Both for DTW and Frechet
* Analysis of the produced bucket system

Produces:
* JSON file containing buckets
* Similarity values for trajectories within buckets

## Hybrid approach

In [1]:
import os
import sys

def find_project_root(target_folder="masteroppgave"):
    """Find the absolute path of a folder by searching upward."""
    currentdir = os.path.abspath("__file__")  # Get absolute script path
    while True:
        if os.path.basename(currentdir) == target_folder:
            return currentdir  # Found the target folder
        parentdir = os.path.dirname(currentdir)
        if parentdir == currentdir:  # Stop at filesystem root
            return None
        currentdir = parentdir  # Move one level up

# Example usage
project_root = find_project_root("masteroppgave")

if project_root:
    sys.path.append(project_root)
    print(f"Project root found: {project_root}")
else:
    raise RuntimeError("Could not find 'masteroppgave' directory")

from computation.similarity import *
from utils.helpers.bucket_evaluation import *
import json
import pandas as pd

Project root found: c:\Users\eivin\dev\JoonEndreLSH\masteroppgave

In [3]:
CITY = "rome" # "rome" or "porto"
MEASURE = "dtw" # "dtw" or "frechet"
BUCKETING_METHOD = "loose" # Bucketing method to use
TRUE_TRAJECTORIES = False # Use true trajectories or not

# Define parameter ranges, first value in list is parameters used for bucketing, second is parameters used for comparing trajectories with each other (using a hashed version of the trajectory) 
DIAMETER_VALUES = [1.6, 0.5]  # Example diameters
LAYERS_VALUES = [4, 6]  # Example layers
DISKS_VALUES = [50, 50]  # Example disk counts
SIZE = 100  # Example dataset sizes

In [4]:
file_path = f"../../../results_true/similarity_values/{CITY}/{MEASURE}/{CITY}-{MEASURE}-{SIZE}.csv"

# Read CSV, telling pandas to take the first column as the row labels:
true_sim_matrix_df = pd.read_csv(file_path, index_col=0)

# Function to convert values to float if possible
def convert_to_float(value):
    try:
        return float(value)
    except ValueError:
        return value

# Apply the function to each cell in the DataFrame
true_sim_matrix_df = true_sim_matrix_df.map(convert_to_float)
true_sim_matrix_df = (true_sim_matrix_df + true_sim_matrix_df.T)

In [5]:
hashed_similarities, bucket_system = generate_disk_hash_similarity_with_bucketing_hybrid(
    city=CITY, diameter=DIAMETER_VALUES, layers=LAYERS_VALUES, disks=DISKS_VALUES, measure=MEASURE, size=SIZE, bucketing_method=BUCKETING_METHOD
    )

[[array([41.91595558, 12.49534511]), array([41.90057705, 12.4923658 ]), array([41.90219048, 12.49900303]), array([41.90805772, 12.49916975]), array([41.8988004 , 12.47814309]), array([41.89295192, 12.47762029])], [array([41.91543848, 12.4975242 ]), array([41.91733224, 12.49481608]), array([41.92067389, 12.49098985]), array([41.90766781, 12.49500938]), array([41.90693077, 12.49207022]), array([41.91119345, 12.48460904]), array([41.90037824, 12.47490241])], [array([41.90966322, 12.48221233]), array([41.90736571, 12.4977333 ]), array([41.89340881, 12.48847136]), array([41.89552247, 12.47811048]), array([41.90256047, 12.48049158])], [array([41.90698635, 12.48291213]), array([41.89582102, 12.48497675]), array([41.90045099, 12.48125003]), array([41.89254543, 12.48924579])]]
[[array([41.90135778, 12.48973992]), array([41.90108345, 12.49167888])], [array([41.91818489, 12.4915877 ])], [array([41.90803346, 12.48898624]), array([41.90743386, 12.48981997]), array([41.90166735, 12.48681871])], [array([41.91550948, 12.49336405])], [array([41.90423331, 12.49378547]), array([41.89562126, 12.47837476])], []]

In [6]:

# hashed_similarities.head(40)
#bucket system to json
with open(f"bucket_system.json", "w") as f:
    
    json.dump(bucket_system, f)

In [7]:
hashed_similarities.head(20)

,R_ABI,R_ABU,R_ABV,R_ACS,R_ADV,R_AFZ,R_AGV,R_AIT,R_AJV,R_AKK,...,R_ECN,R_ECP,R_EDS,R_EDX,R_EEB,R_EFS,R_EHK,R_EIC,R_ENE,R_ENH
R_ABI,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_ABU,0.479025,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_ABV,0.316191,0.134695,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_ACS,0.000000,0.460568,0.330559,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_ADV,0.144421,0.448653,0.353679,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_AFZ,0.285339,0.280639,0.198731,0.000000,0.348536,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_AGV,0.394323,0.155452,0.137569,0.434353,0.404879,0.317233,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_AIT,0.000000,0.167701,0.000000,0.000000,0.000000,0.516795,0.368854,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_AJV,0.324782,0.212566,0.335869,0.000000,0.380839,0.344123,0.000000,0.288361,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_AKK,0.498975,0.257049,0.239517,0.470746,0.544066,0.391131,0.151872,0.412695,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_AKY,0.475259,0.106126,0.209559,0.398908,0.566806,0.344327,0.253792,0.117582,0.000000,0.178490,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_APP,0.035301,0.357800,0.286000,0.000000,0.174426,0.320618,0.312342,0.000000,0.357465,0.389788,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_APX,0.316328,0.282608,0.178015,0.328024,0.377610,0.239489,0.294604,0.000000,0.462250,0.327860,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_ARC,0.418654,0.320798,0.252967,0.526843,0.391532,0.401593,0.140013,0.446338,0.000000,0.022849,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_ARP,0.388641,0.258175,0.132463,0.000000,0.408411,0.231813,0.264070,0.387035,0.319775,0.289920,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_ARU,0.489462,0.095837,0.254023,0.000000,0.507605,0.321455,0.262636,0.227526,0.141147,0.335705,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_AVB,0.324823,0.128368,0.112035,0.467346,0.312483,0.236352,0.071953,0.268055,0.000000,0.052487,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_AVD,0.554921,0.140051,0.232876,0.000000,0.722434,0.325477,0.288145,0.327580,0.415821,0.284266,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_AVF,0.302400,0.100925,0.101624,0.451664,0.303908,0.215407,0.136265,0.231459,0.326161,0.142460,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_AVK,0.326949,0.262929,0.185873,0.478415,0.350027,0.221067,0.203289,0.426858,0.000000,0.188853,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
index1 = "R_ADV"
index2 = "R_ABU"
value = true_sim_matrix_df.loc[index1, index2]
print(f"The value at index ({index1}, {index2}) is: {value}")

The value at index (R_ADV, R_ABU) is: 2.565742737913063

In [9]:
total_buckets = len(bucket_system)
buckets_with_multiple = sum(1 for trajectories in bucket_system.values() if len(trajectories) > 1)
buckets_with_single = total_buckets - buckets_with_multiple
largest_bucket_size = max(len(trajectories) for trajectories in bucket_system.values())
largest_bucket = max(bucket_system, key=lambda key: len(bucket_system[key]))
smallest_bucket = min(bucket_system, key=lambda key: len(bucket_system[key]))
smallest_bucket_size = len(bucket_system[smallest_bucket])


print(f"Total Buckets: {total_buckets}")
print(f"Largest Bucket(id): {largest_bucket}")
print(f"Buckets with more than one trajectory: {buckets_with_multiple}")
print(f"Buckets with only one trajectory: {buckets_with_single}")
print(f"Largest Bucket Size: {largest_bucket_size}")
print("smallest bucket: ", smallest_bucket_size)

# Optional: Display distribution percentages
multiple_bucket_percentage = (buckets_with_multiple / total_buckets) * 100 if total_buckets > 0 else 0
single_bucket_percentage = (buckets_with_single / total_buckets) * 100 if total_buckets > 0 else 0

print(f"Percentage of buckets with more than one trajectory: {multiple_bucket_percentage:.2f}%")
print(f"Percentage of buckets with only one trajectory: {single_bucket_percentage:.2f}%")

Total Buckets: 180
Largest Bucket(id): 316838604522342515050443944331075534350
Buckets with more than one trajectory: 172
Buckets with only one trajectory: 8
Largest Bucket Size: 69
smallest bucket:  1
Percentage of buckets with more than one trajectory: 95.56%
Percentage of buckets with only one trajectory: 4.44%

In [11]:
# THRESHOLD = 5
import numpy as np # type: ignore
THRESHOLDS = np.arange(1, 6.0, 1)  # Generates [0.5, 1.0, 1.5, ..., 5.5]

results = {
    "Precision": [],
    "Recall": [],
    "F1 Score": []
}



for treshold in THRESHOLDS:

    #Variables
    all_trajectory_names = list(hashed_similarities.keys()) # All trajectory names
    true_positives = 0
    false_positives = 0
    false_negatives = 0
    precision = 0 
    recall = 0
    f1_Score = 0

    # Loop through all trajectory names
    for trajectory in all_trajectory_names:
        
        
        # Pred and ground truth
        predicted_similar = find_predicted_similar_trajectories(trajectory, bucket_system)
        ground_truth = get_nearest_neighbour_under_threshold(trajectory, treshold, true_sim_matrix_df).index.to_list()
        true_positives += calculate_true_positives(predicted_similar, ground_truth)
        false_positives += calculate_false_positives(predicted_similar, ground_truth)
        false_negatives += calculate_false_negatives(predicted_similar, ground_truth)
        # print("num predicted similar" , len(predicted_similar))
        # print("num ground truth" , len(ground_truth))

        # print(trajectory, "predicted similar: ", predicted_similar)
        # print(trajectory, "ground truth: ", ground_truth)
        # print("True positives: ", true_positives)
        # print("False positives: ", false_positives)
        # break
        

    # Calculate precision and recall
    precision = compute_bucket_system_precision(true_positives, false_positives)
    recall = compute_bucket_system_recall(true_positives, false_negatives)
    f1_score = compute_bucket_system_f1_score(precision, recall)

    results["Precision"].append(precision)
    results["Recall"].append(recall)
    results["F1 Score"].append(f1_score)
    
    
print(f"Bucket system statistics for city: {CITY}, measure: {MEASURE}, diameter: {DIAMETER_VALUES}, layers: {LAYERS_VALUES}, disks: {DISKS_VALUES}, size: {SIZE}")
# Create DataFrame with thresholds as columns and metrics as row indexes
df = pd.DataFrame(results, index=[f"Threshold = {t}" for t in THRESHOLDS]).T

df

Bucket system statistics for city: rome, measure: dtw, diameter: [1.6, 0.5], layers: [4, 6], disks: [50, 50], size: 100

,Threshold = 1.0,Threshold = 2.0,Threshold = 3.0,Threshold = 4.0,Threshold = 5.0
Precision,0.188480,0.600245,0.816422,0.916422,0.959559
Recall,1.000000,0.961146,0.914859,0.879558,0.857424
F1 Score,0.317179,0.738986,0.862842,0.897611,0.905621