# Notebook for computing hashes, buckets and similarity values for the grid scheme. 

Utilizes the grid scheme

Incorporates:
* Hashing of trajectories using grid scheme
* Bucketing of hashes made from grid scheme
* Similarity computation between trajectories within buckets.
    * Both for DTW and Frechet
* Analysis of the produced bucket system

Produces:
* JSON file containing buckets
* Similarity values for trajectories within buckets

In [23]:

# Importing nescessary modules
import os
import sys

def find_project_root(target_folder="masteroppgave"):
    """Find the absolute path of a folder by searching upward."""
    currentdir = os.path.abspath("__file__")  # Get absolute script path
    while True:
        if os.path.basename(currentdir) == target_folder:
            return currentdir  # Found the target folder
        parentdir = os.path.dirname(currentdir)
        if parentdir == currentdir:  # Stop at filesystem root
            return None
        currentdir = parentdir  # Move one level up

# Example usage
project_root = find_project_root("masteroppgave")

if project_root:
    sys.path.append(project_root)
    print(f"Project root found: {project_root}")
else:
    raise RuntimeError("Could not find 'masteroppgave' directory")


#Other imports
from computation.similarity import *
from utils.helpers.bucket_evaluation import *
import json
import pandas as pd

Project root found: /Users/thomasnitsche/Developer/skole/master/masteroppgave

# Setup

In [24]:
CITY = "rome" # "rome" or "porto"
MEASURE = "dtw" # "dtw" or "frechet"
RESOLUTION = 2 # Resolution of the grid
LAYERS = 3 # Number of layers
SIZE = 50 #How many trajectories to use

#Strategies
BUCKETING_METHOD = "original" #Bucketing method to use
TRUE_TRAJECTORIES = True #Use true trajectories or not

## Retrieving the true similarity values

In [25]:
file_path = f"../../../results_true/similarity_values/{CITY}/{MEASURE}/{CITY}-{MEASURE}-{SIZE}.csv"

# Read CSV, telling pandas to take the first column as the row labels:
true_sim_matrix_df = pd.read_csv(file_path, index_col=0)

# Function to convert values to float if possible
def convert_to_float(value):
    try:
        return float(value)
    except ValueError:
        return value

# Apply the function to each cell in the DataFrame
true_sim_matrix_df = true_sim_matrix_df.map(convert_to_float)
true_sim_matrix_df = (true_sim_matrix_df + true_sim_matrix_df.T)

## Generate hashes with grid scheme, bucket system and similarity values for the given city and measure

In [26]:
if TRUE_TRAJECTORIES:
    print("running with true trajectories")        
    hashed_similarities, bucket_system = generate_grid_hash_similarity_with_bucketing_with_true_sim(
        city=CITY, res=RESOLUTION, layers=LAYERS, measure=MEASURE, size=SIZE, bucketing_method=BUCKETING_METHOD
    )

else:
    print("running with hashes")
    hashed_similarities, bucket_system = generate_grid_hash_similarity_with_bucketing(
        city=CITY, res=RESOLUTION, layers=LAYERS, measure=MEASURE, size=SIZE, bucketing_method=BUCKETING_METHOD
    )

running with true trajectories

In [27]:
hashed_similarities.head(40)

,R_ABU,R_ADV,R_AFZ,R_AKK,R_AKY,R_ARC,R_ARU,R_AVB,R_AVD,R_AVF,...,R_DUV,R_DVK,R_DYX,R_EBK,R_ECN,R_ECP,R_EDS,R_EDX,R_EFS,R_EHK
R_ABU,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_ADV,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_AFZ,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_AKK,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_AKY,1.732655,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_ARC,0.000000,0.000000,0.000000,0.201367,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_ARU,0.348730,0.000000,0.000000,0.000000,1.165095,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_AVB,0.000000,0.000000,0.000000,0.000000,0.000000,1.100653,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_AVD,0.000000,0.000000,1.364519,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_AVF,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_AVK,0.000000,0.000000,0.470519,0.000000,0.000000,0.000000,0.000000,0.000000,2.563121,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_AWU,0.000000,0.000000,0.619110,0.000000,0.000000,0.000000,0.000000,0.000000,1.310844,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_AZS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_BCU,1.368580,0.000000,0.000000,0.000000,0.476347,0.000000,1.022301,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_BDC,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_BFS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_BML,0.000000,1.224785,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_BNG,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_BRF,0.000000,0.000000,0.000000,1.273316,0.000000,0.520267,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_BTH,0.000000,0.000000,0.517957,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_BUX,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_CAV,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_CCJ,0.000000,0.000000,1.827822,0.000000,0.000000,0.000000,0.000000,0.000000,4.222561,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_CCQ,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_CCZ,1.346100,0.000000,0.000000,0.000000,0.863135,0.000000,0.863083,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_CDU,0.000000,0.000000,0.687636,0.000000,0.000000,0.828901,0.000000,0.730634,1.028487,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_CEX,0.000000,0.000000,0.000000,0.414465,0.000000,0.141953,0.000000,1.663291,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_CFV,2.132188,0.000000,0.000000,0.000000,0.529825,0.000000,1.650639,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_CIV,0.649147,0.000000,0.000000,0.000000,0.892915,0.000000,0.747835,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_CNH,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_COQ,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.941497,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_CPD,0.000000,0.000000,0.000000,0.000000,0.000000,0.965820,0.000000,3.566721,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_CRC,0.000000,0.000000,0.000000,0.000000,0.000000,0.361214,0.000000,0.321753,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_CYW,0.440494,0.000000,0.000000,0.000000,0.778722,0.000000,0.435723,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_DAQ,1.407538,0.000000,0.000000,0.000000,0.687269,0.000000,1.261949,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_DDN,0.000000,0.000000,2.657615,0.000000,0.000000,0.000000,0.000000,0.000000,2.743090,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_DGV,0.000000,0.000000,0.425796,0.000000,0.000000,0.000000,0.000000,0.000000,5.076096,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_DJT,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_DOY,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.537067,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
R_DUB,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Bucket analysis

## Bucket stats

In [ ]:
total_buckets = len(bucket_system)
largest_bucket = max(bucket_system, key=lambda key: len(bucket_system[key]))
largest_bucket_size = max(len(trajectories) for trajectories in bucket_system.values())
buckets_with_multiple = sum(1 for trajectories in bucket_system.values() if len(trajectories) > 1)
buckets_with_single = total_buckets - buckets_with_multiple
avg_number_of_trajectories_per_bucket = sum(len(trajectories) for trajectories in bucket_system.values()) / total_buckets
smallest_bucket = min(bucket_system, key=lambda key: len(bucket_system[key]))
smallest_bucket_size = min(len(trajectories) for trajectories in bucket_system.values())


print(f"Total Buckets: {total_buckets}")
print(f"Largest Bucket(id): {largest_bucket}")
print(f"Largest Bucket Size: {largest_bucket_size}")
print(f"Smallest Bucket Size: {smallest_bucket_size}")

print(f"Buckets with more than one trajectory: {buckets_with_multiple}")
print(f"Buckets with only one trajectory: {buckets_with_single}")
print(f"Average number of trajectories per bucket: {avg_number_of_trajectories_per_bucket:.2f}")


# Optional: Display distribution percentages
multiple_bucket_percentage = (buckets_with_multiple / total_buckets) * 100 if total_buckets > 0 else 0
single_bucket_percentage = (buckets_with_single / total_buckets) * 100 if total_buckets > 0 else 0

print(f"Percentage of buckets with more than one trajectory: {multiple_bucket_percentage:.2f}%")
print(f"Percentage of buckets with only one trajectory: {single_bucket_percentage:.2f}%")

Total Buckets: 90
Largest Bucket(id): 105314878385590514801839183158254873091
Largest Bucket Size: 11
Smallest Bucket Size: 1
Buckets with more than one trajectory: 27
Buckets with only one trajectory: 63
Average number of trajectories per bucket: 1.67
Percentage of buckets with more than one trajectory: 30.00%
Percentage of buckets with only one trajectory: 70.00%

## TP, FP, FN, PRECISION, RECALL

In [29]:
import numpy as np # type: ignore

THRESHOLDS = np.arange(1, 6.0, 1)  # Generates [0.5, 1.0, 1.5, ..., 5.5]

results = {
    "Precision": [],
    "Recall": [],
    "F1 Score": []
}

for treshold in THRESHOLDS:


    #Variables
    all_trajectory_names = list(hashed_similarities.keys()) # All trajectory names
    true_positives = 0
    false_positives = 0
    false_negatives = 0
    precision = 0 
    recall = 0
    f1_Score = 0

    # Loop through all trajectory names
    for trajectory in all_trajectory_names:
        
        # Pred and ground truth
        predicted_similar = find_predicted_similar_trajectories(trajectory, bucket_system)
        ground_truth = get_nearest_neighbour_under_threshold(trajectory, treshold, true_sim_matrix_df).index.to_list()  
        true_positives += calculate_true_positives(predicted_similar, ground_truth)
        false_positives += calculate_false_positives(predicted_similar, ground_truth)
        false_negatives += calculate_false_negatives(predicted_similar, ground_truth)


    # Calculate precision and recall
    precision = compute_bucket_system_precision(true_positives, false_positives)
    recall = compute_bucket_system_recall(true_positives, false_negatives)
    f1_score = compute_bucket_system_f1_score(precision, recall)
    
    results["Precision"].append(precision)
    results["Recall"].append(recall)
    results["F1 Score"].append(f1_score)

print(f"Bucket system statistics for city: {CITY}, measure: {MEASURE}, resolution: {RESOLUTION}, layers: {LAYERS}, size: {SIZE}")
df = pd.DataFrame(results, index=[f"Threshold = {t}" for t in THRESHOLDS]).T

df

Bucket system statistics for city: rome, measure: dtw, resolution: 2, layers: 3, size: 50

,Threshold = 1.0,Threshold = 2.0,Threshold = 3.0,Threshold = 4.0,Threshold = 5.0
Precision,0.493151,0.876712,0.965753,0.979452,0.993151
Recall,0.376963,0.193062,0.151613,0.131676,0.124892
F1 Score,0.427300,0.316440,0.262082,0.232143,0.221882